CREATE DATABASE MEU_NOVO_FORMULARIO
GO

USE MEU_NOVO_FORMULARIO
GO

CREATE TABLE PESSOAS
(
	PESSOA_ID INT IDENTITY (1, 1),
	NOME_COMPLETO VARCHAR(150),
	IDADE TINYINT,
	PROFISSAO VARCHAR(50),
	CPF VARCHAR(11) NOT NULL,
	DATA_NASCIMENTO TIME,
	FRASE VARCHAR(500),
	ULTIMA_ATUALIZACAO DATETIME

	CONSTRAINT PK_PESSOAS_ID PRIMARY KEY (PESSOA_ID) 

)

CREATE TABLE ENDERECOS
(
	ENDERECO_ID INT IDENTITY (1, 1),
	PESSOA_ID INT NULL,
	LOGRADOURO VARCHAR(100),
	NUMERO INT,
	COMPLEMENTO VARCHAR(20),
	BAIRRO VARCHAR(100),
	CIDADE VARCHAR(100),
	ESTADO VARCHAR(100),
	PAIS VARCHAR(100),
	CEP INT,
	PONTO_REFERENCIA VARCHAR(100) NULL,

	CONSTRAINT PK_ENDERECOS_ENDERECO_ID PRIMARY KEY (ENDERECO_ID),
	CONSTRAINT FK_ENDERECOS_PESSOAS_PESSOA_ID FOREIGN KEY (PESSOA_ID)
	REFERENCES PESSOAS (PESSOA_ID)

)

ALTER TABLE PESSOAS DROP COLUMN DATA_NASCIMENTO
ALTER TABLE PESSOAS ADD  DATA_NASCIMENTO DATE
ALTER TABLE ENDERECOS ALTER COLUMN CEP VARCHAR(8)
ALTER TABLE PESSOAS ADD DATA_CADASTRO DATETIME2 NULL DEFAULT GETDATE() 
ALTER TABLE ENDERECOS ALTER COLUMN ESTADO CHAR(2)

ALTER TABLE PESSOAS
ADD CONSTRAINT DF_PESSOAS_ULTIMA_ATUALIZACAO DEFAULT (GETDATE()) FOR ULTIMA_ATUALIZACAO

ALTER TABLE PESSOAS
ADD CONSTRAINT UQ_PESSOAS_CPF UNIQUE(CPF)

ALTER TABLE ENDERECOS
ADD CONSTRAINT DF_ENDERECOS_CEP DEFAULT ('00000000') FOR CEP

ALTER TABLE ENDERECOS
ALTER COLUMN COMPLEMENTO VARCHAR(20) NULL

select * from PESSOAS

select * from ENDERECOS




